; Easy Picross levels
	const_def
	const LEVEL_HOME

; Town Map levels
	const_def
	const LEVEL_TOKIWA_FOREST
	const LEVEL_MT_OTSUKIMI
	const LEVEL_SEA_COTTAGE
	const LEVEL_S_S_ANNE
	const LEVEL_POKEMON_TOWER
	const LEVEL_SILPH_COMPANY
	const LEVEL_CYCLING_ROAD
	const LEVEL_POWER_PLANT
	const LEVEL_FUTAGO_ISLAND
	const LEVEL_HANADA_CAVE
	const LEVEL_MEW

; Safari Zone levels
	const_def
	const LEVEL_PLAIN_ZONE
	const LEVEL_LAKE_ZONE
	const LEVEL_MOUNTAIN_ZONE
	const LEVEL_JUNGLE_ZONE
